spring:
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        current_session_context_class: thread
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver